site_name: 自動運転 AI チャレンジ 2026
site_url: https://automotiveaichallenge.github.io/aichallenge-documentation-racingkart/
repo_url: https://github.com/AutomotiveAIChallenge/aichallenge-documentation-racingkart
docs_dir: docs
copyright: "&copy; 2026 TIER IV, Inc."
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - announce.dismiss
  palette:
    scheme: slate
    primary: custom
    accent: custom
    # logo:

extra:
  gtm_id: !ENV GTM_ID

nav:
  - index: index.md
  - getting-started.md
  - preliminaries:
      - preliminaries/rules.md
      - preliminaries/submission.md
      - preliminaries/check-results.md
  - finals:
      - finals/index.md
  - setup:
      - setup/requirements.md
      - setup/workspace-setup.md
      - setup/docker.md
      - setup/headless-simulation.md
      - setup/visible-simulation.md
      - setup/build-docker.md
      - setup/reference.md
  - development:
      - development/workspace-usage.md
      - development/main-module.md
  - specifications:
      - specifications/interface.md
      - specifications/hardware.md
      - specifications/simulator.md
  - course:
      - course/index.md
      - course/vehicle.md
      - course/velocity_planning.md
      - course/avoidance.md
      - course/localization.md
  - ML:
      - ai.md
      - ml_sample/algorithms.md
      - ml_sample/getting_started_tiny_lidar_net.md
      - ml_sample/design.md
      - ml_sample/getting_started_vlm_setup.md
      - ml_sample/getting_started_vlm_run.md
      - ml_sample/getting_started_vad_setup.md
      - ml_sample/getting_started_vad_run.md
      - ml_sample/faq.md
  - FAQ: faq.md
  - Community: community.md

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          default: true
          name: 日本語
          build: true
          nav_translations:
            index: 競技概要
            preliminaries: 予選
            finals: 決勝
            setup: 環境構築
            development: 開発
            specifications: 仕様
            course: 入門講座
            ML: AI講座
            Community: コミュニティ
        - locale: en
          name: English
          build: true
          nav_translations:
            index: Top Page
            preliminaries: Preliminaries
            setup: Setup
            development: Development
            specifications: Specifications
            course: Course
  - link-preview:
